/node/delete should use node_id
Otherwise test_delete_node would fail with:

   AssertionError: 400 != 200 : Response body is : {
     "detail": "'id' is a required property",
     "status": 400,
     "title": "Bad Request",
     "type": "about:blank"
   }